# Generated by Django 3.1.5 on 2021-01-15 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0005_questionoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveyee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Анкетируемый',
                'verbose_name_plural': 'Анкетируемые',
            },
        ),
        migrations.CreateModel(
            name='SurveyeeSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey')),
                ('surveyee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.surveyee', verbose_name='Анкетируемый')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(max_length=1000)),
                ('question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.questionoption')),
                ('surveyee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.surveyee')),
            ],
        ),
    ]
