# Generated by Django 3.1.5 on 2021-01-19 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_auto_20210119_2358'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0003_auto_20210116_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyeesurvey',
            name='creator',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(max_length=1000, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.questionoption', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='surveyee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.surveyee', verbose_name='Анкетируемый'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.optionchoice', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='surveyeesurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey', verbose_name='Анкета'),
        ),
    ]
