# Generated by Django 3.1.5 on 2021-01-19 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0006_answer_answer_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.surveyeesurvey', verbose_name='Набор ответов'),
        ),
    ]
