# Generated by Django 3.1.5 on 2021-01-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0007_auto_20210120_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст ответа'),
        ),
    ]
