# Generated by Django 3.1.5 on 2021-01-19 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0008_auto_20210120_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='surveyeesurvey',
            options={'verbose_name': 'Набор ответов', 'verbose_name_plural': 'Наборы ответов'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='surveyee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='answers.surveyee', verbose_name='Анкетируемый'),
        ),
    ]
