# Generated by Django 3.1.5 on 2021-01-14 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='Тип вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_title', models.CharField(max_length=200, verbose_name='Название анкеты')),
                ('creation_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('is_open', models.BooleanField(verbose_name='Открыто для заполнения')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=500, verbose_name='Вопрос')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.questiontype')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey')),
            ],
        ),
    ]
