# Generated by Django 3.1.5 on 2021-01-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='survey_id',
            new_name='survey',
        ),
    ]
