# Generated by Django 3.1.5 on 2021-01-15 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0003_survey_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='Тип ответа')),
            ],
            options={
                'verbose_name': 'Тип ответов',
                'verbose_name_plural': 'Типы ответов',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questiontype',
            options={'verbose_name': 'Тип вопросов', 'verbose_name_plural': 'Типы вопросов'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Анкета', 'verbose_name_plural': 'Анкеты'},
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_desc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание анкеты'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.questiontype', verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey', verbose_name='Анкета'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200, verbose_name='Название секции')),
                ('section_desc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание секции')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Секция анкеты',
                'verbose_name_plural': 'Секции анкеты',
            },
        ),
        migrations.CreateModel(
            name='OptionChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Вариант ответа')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.optiongroups', verbose_name='Тип ответов')),
            ],
            options={
                'verbose_name': 'Вариант ответов',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='option_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.optiongroups', verbose_name='Тип ответа'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surveys.section', verbose_name='Секция'),
        ),
    ]
