# Generated by Django 3.1.5 on 2021-01-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_questionoptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptionChoices',
            new_name='OptionChoice',
        ),
        migrations.RenameModel(
            old_name='OptionGroups',
            new_name='OptionGroup',
        ),
        migrations.RenameModel(
            old_name='QuestionOptions',
            new_name='QuestionOption',
        ),
    ]
