# Generated by Django 3.1.5 on 2021-01-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20210116_1058'),
        ('surveys', '0007_remove_question_survey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
