# Generated by Django 3.2.4 on 2021-06-26 18:44

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210624_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', hashid_field.field.BigHashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', auto_created=True, min_length=13, prefix='', primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название секции')),
                ('desc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание секции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Секция анкеты',
                'verbose_name_plural': 'Секции анкеты',
            },
        ),
    ]
