# Generated by Django 3.2.4 on 2021-06-26 19:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
