# Generated by Django 3.2.4 on 2021-06-26 19:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20210626_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
