# Generated by Django 3.2.4 on 2021-07-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_answer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=1000, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='section',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
